# Generated by Django 4.2.4 on 2023-08-27 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='photo',
            new_name='posted_photo',
        ),
    ]
