# Generated by Django 4.2.4 on 2023-08-27 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0002_rename_photo_post_posted_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='posted_photo',
            field=models.ImageField(blank=True, null=True, upload_to='post_by_<django.db.models.fields.related.ForeignKey>'),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
