# Generated by Django 4.2.4 on 2023-08-30 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0002_friendlist_friends_since'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendlist',
            name='friends_since',
        ),
    ]
